server:
  port: 8222

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         - id: service-edu
           uri: lb://service-edu
           predicates:
             - Path=/eduservice/**
         - id: service-msm
           uri: lb://service-msm
           predicates:
             - Path=/msmservice/**

